In [1]:
import numpy as np
import pandas as pd
a =np.array([[1, 2, 3]],dtype=float)

a.shape # 1 is here : 1 is rows and 3 is columns

(1, 3)

In [2]:
a =np.array([[1, 2, 3],[1, 2, 3]],dtype=float)
a.shape # 2 is here : 2 is rows and 3 is columns

(2, 3)

In [3]:
mix_array = np.array([1,2,3,'23','24.5'],dtype=float)
mix_array.dtype
mix_array

array([ 1. ,  2. ,  3. , 23. , 24.5])

In [4]:
# access elements again using index
mix_array[0], mix_array[1], mix_array[2]

(np.float64(1.0), np.float64(2.0), np.float64(3.0))

In [5]:
# slicing
mix_array[0:3]

array([1., 2., 3.])

In [6]:
sum=0
for i in mix_array:
    sum += i

sum

np.float64(53.5)

In [7]:
a =[1,2,3,'23']

sum = 0
for i in a:
    sum += float(i)

In [9]:
# pd.DataFrame(a,columns=['col1','col2','col3'])

In [15]:
a = np.arange(10)
print(a)
a[5]


a = np.diag([1,2,3])
a

[0 1 2 3 4 5 6 7 8 9]


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
a[0,1] = 5
a

array([[1, 5, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [20]:
# slicing here
a[0:2, 1] # here 0 means the starting index and 2 
# means the ending index (exclusive) and 1 
# means the column index we want to access


array([5, 2])

In [22]:
a[0:2, 0:2]

array([[1, 5],
       [0, 2]])

In [25]:
c = np.diag([1,2,3])
c*c

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [26]:
c.dot(c)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [33]:
a = np.array([[2,3],[4,5]])
print(a.shape)

b = np.array([[1,2,3],[4,5,6]])
b.shape

a.dot(b)

(2, 2)


array([[14, 19, 24],
       [24, 33, 42]])

In [35]:
a = np.array([1,1,0,0],dtype=bool)
b = np.array([0,1,0,1],dtype=bool)
a | b

array([ True,  True, False,  True])

In [38]:
# shape mismatch
a = np.arange(4)
b = np.array([1,2])
print(a.shape)
print(b.shape)
print(a)
print(b)
a+b

(4,)
(2,)
[0 1 2 3]
[1 2]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [40]:
b.reshape(2,1) # here 2 means rows and 1 means column

array([[1],
       [2]])

In [41]:
a+ b.reshape(2,1)

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [42]:
x = np.array([[1,4],[2,2]])
x

array([[1, 4],
       [2, 2]])

In [45]:
x.sum(axis=0) # here axis=0 means we want to sum along the columns
x.sum(axis=1) # here axis=1 means we want to sum along the rows

array([5, 4])

In [47]:
x.min(axis=0) # here axis=0 means we want to find the minimum along the columns
# x.min(axis=1) # here axis=1 means we want to find the minimum along the rows

array([1, 2])

In [56]:
# lets create dummy stock data
stock_price = np.random.standard_normal((100,4))
stock_price.mean(axis=0) # here axis=0 means we want to sum along the columns    

array([-0.03430567,  0.04676157, -0.12964368, -0.0875661 ])

In [52]:
stock_price

array([[ 1.18885657, -0.17983611,  0.4990933 , -0.14487581],
       [ 1.0104262 ,  0.25791624, -0.19232312,  1.37217437],
       [ 0.23607608, -1.41075024, -0.50078459,  1.65509403],
       [ 1.49589711,  0.57228876, -0.79786365,  0.86858495],
       [ 0.20161691,  1.28438625, -1.01472495, -0.90612394],
       [-1.05404355, -1.30364953, -0.60467558,  0.03606536],
       [ 1.02369478, -0.29111931, -0.10678693, -0.37767288],
       [-0.45932583,  0.18133611, -0.54875744,  0.20623787],
       [-0.55610819,  0.01422184, -1.35955416, -0.3360703 ],
       [ 1.18142617, -1.07634506, -0.65553124,  0.52756755],
       [-2.76770979,  0.86879873, -1.74050367, -1.74947291],
       [ 0.78234611, -0.49398431, -0.59032835,  0.38822014],
       [ 0.55329358, -0.51996324, -0.74271258, -0.89348451],
       [ 0.59558999, -0.24405083,  0.49357633,  0.37594367],
       [ 0.28399614, -0.1631191 , -1.44964896, -0.5557327 ],
       [ 0.02159554,  0.8570744 , -1.18039144,  0.5119869 ],
       [ 1.43006839, -1.

In [62]:
x.argmax(axis=0) # index of maximum value along the columns
x.argmax(axis=1) # index of maximum value along the rows

array([1, 0])

In [63]:
x.argmin(axis=0) # index of minimum value along the columns
x.argmin(axis=1) # index of minimum value along the rows

array([0, 0])

In [ ]:
# mean, variance, std-dev, MAD